// Stub for command palette config.json — a virtual ResourceLoader module
// generated by ResourceLoaderHooks::getCitizenSearchResourceLoaderConfig.
module.exports = {
	isMediaSearchExtensionEnabled: false,
	wgSearchSuggestCacheExpiry: 1200
};
