// Stub for command palette config.json — a virtual ResourceLoader module
// generated by ResourceLoaderHooks::getCitizenCommandPaletteResourceLoaderConfig.
module.exports = {
	isMediaSearchExtensionEnabled: false,
	isSemanticMediaWikiEnabled: false,
	wgSearchSuggestCacheExpiry: 1200
};
