// Stub for command palette config.json — a virtual ResourceLoader module
// generated by ResourceLoaderHooks::getCitizenCommandPaletteResourceLoaderConfig.
module.exports = {
	isBucketEnabled: false,
	bucketNamespaceId: 9592,
	isSemanticMediaWikiEnabled: false,
	wgSearchSuggestCacheExpiry: 1200
};
