// Stub for command palette specialPages.json — a virtual ResourceLoader module
// generated by ResourceLoaderHooks::getCitizenCommandPaletteSpecialPages.
// English names, except that Version is localised, as on a wiki whose content
// language names it Версия and keeps its English name as an alias.
module.exports = [
	'Search',
	[ 'Listfiles', 'ListFiles', 'FileList', 'ImageList' ],
	[ 'Contributions', 'Contributions', 'Contribs' ],
	[ 'Version', 'Версия', 'Version' ]
];
