// Stub for preferences config.json — a virtual ResourceLoader module
// generated by ResourceLoaderHooks::getCitizenPreferencesResourceLoaderConfig.
module.exports = {
	wgCitizenThemeDefault: 'auto'
};
