name: Grunt

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
        npm install --save-dev

    #- name: Generate documentation
    #  run: npm run doc

    - name: Run stylelint autofix
      run: npm run fix
      
    - name: Run Grunt test
      run: npm run test

    - name: Push the changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git add .
        git commit -am "Github CI lint - eslint/stylelint"
        git push
